# Generated by Django 5.1.6 on 2025-02-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
